language: java
install: true
sudo: required
services:
  - docker
jdk:
  - openjdk8

script:
  - watch docker ps &
  - ./gradlew clean integrationTest --tests com.solace.messaging.kafka.it.SourceConnectorIT