name=solaceSourceConnector
connector.class=com.solace.source.connector.SolaceSourceConnector
tasks.max=1
kafka.topic=test
sol.host=tcp://mr1u6o37qn3lar.messaging.solace.cloud:55555
sol.username=solace-cloud-client
sol.password=e5l4l6u334fj02tnhnm00obi7c
sol.vpn_name=b-1
#sol.topics=soltest, soltest1,solacetest2
sol.topics=sourcetest
#sol.queue=testQ
sol.message_processor_class=com.solace.source.connector.msgprocessors.SolSampleSimpleMessageProcessor
value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
key.converter=org.apache.kafka.connect.storage.StringConverter
