version: '3'

services:
  kafka-connector:
    image: confluentinc/cp-kafka:5.1.1
    hostname: kafka-connector
    depends_on:
      - kafka
      - zookeeper
    volumes:
      - pubsubplus-connector-kafka-source:/tmp/pubsubplus-connector-kafka-source
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
                 cub kafka-ready -b kafka:9092 1 30 && \
                 kafka-topics --create --if-not-exists --zookeeper zookeeper:2181 --partitions 1 --replication-factor 1 --topic $KAFKA_TOPIC && \
                 sleep 30'"
    environment:
      # The following settings are listed here only to satisfy the image's requirements.
      # We override the image's `command` anyways, hence this container will not start a broker.
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
